config:
  model_init_name: "bytetracker"
  inference_cfg:
    track_buffer: 30
    track_thresh: 0.5
    track_high_thresh: 0.6
    track_low_thresh: 0.1
    new_track_thresh: 0.7
    match_thresh: 0.8
    fuse_score: True
    mot20: False

# Faster R-CNN config
#config:
#  model_init_name: "bytetracker"
#  inference_cfg:
#    track_buffer: 300
#    track_thresh: 0.25
#    track_high_thresh: 0.5
#    track_low_thresh: 0.05
#    new_track_thresh: 0.97
#    match_thresh: 0.4
#    fuse_score: True
#    mot20: False